{
    "docs": "https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/import.html",
    "results": [
        {
            "message": "The test `ansible-test sanity --test import --python 3.6` [[explain](https://docs.ansible.com/ansible/devel/dev_guide/testing/sanity/import.html)] failed with 47 errors:",
            "output": "plugins/modules/bk/lcm/extvc/bk-vxlcm.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/lcm/extvc/lcm-dev.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/lcm/extvc/vx_lcm.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/lcm/extvc/vxlcmjp.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/lcm/intvc/lcm.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/lcm/intvc/vx_intlcm.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/lcm/vx_lcm.py:104:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/lcm/vxlcm.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vcmode.py:90:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_addnode.py:117:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_callhome.py:115:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_clusterinfo.py:76:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_diskinfo.py:74:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_extlcm.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_firmware.py:64:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_freenode.py:68:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_health.py:75:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_healthlist.py:75:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_hostinfo.py:76:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_init.py:11:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_lcm.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_logs.py:78:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_netinfo.py:73:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_nodes.py:77:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_ping.py:73:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_rmnode.py:80:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vx_upgrade.py:103:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/bk/vxhealth.py:5:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vcmode.py:9:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx7_extlcm.py:104:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_addnode.py:117:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_callhome.py:115:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_clusterinfo.py:76:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_diskinfo.py:74:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_extlcm.py:104:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_firmware.py:64:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_freenode.py:68:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_health.py:76:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_healthlist.py:75:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_hostinfo.py:76:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_init.py:11:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_lcm.py:104:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_logs.py:78:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_netinfo.py:73:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_nodes.py:77:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_ping.py:73:0: traceback: ModuleNotFoundError: No module named 'requests'\nplugins/modules/vx_rmnode.py:80:0: traceback: ModuleNotFoundError: No module named 'requests'"
        }
    ],
    "verified": false
}
